### ISSUE TITLE
Any chance this could be licensed under Apache 2 instead of LGPL?

### ISSUE THREAD

**Issue by KFishner** [masterzen/xmlpath#1]
Hey there, noticed your other work is licensed under Apache 2. Is there a reason for this one being LGPL?

Thanks!

**Comment by masterzen** [comment]
Hi @KFishner , 

I'm not the original author of this library (I'm just hosting it here with some enhancements), hence I can't change its license.

I tried to contact the author back 3 years ago, but had no chance.

Did a little research this morning and found that the original author apparently hosted [this lib on github](https://github.com/go-xmlpath/xmlpath), but it's still the same license.

Apparently, nowadays, people use [xquery](https://github.com/antchfx/xquery), which is licensed under MIT.

Sorry for the problem.
